import {
  CapabilitySchema,
  CrewMemberSchema,
  CrewPreferenceSchema,
  CrewScheduleSchema,
  DeviceSchema,
  IdentityTagSchema,
  HARD_INVARIANTS,
  MembershipSchema,
  OrganizationSchema,
  PalaceSchema,
  RoutineSchema,
  RoutineVersionSchema,
  UserSchema,
} from '@trash-palace/core'

const CREATED_AT = '2026-08-01T12:00:00-04:00'

/** Pre-mission local state projected from night-shift-homecoming@1. */
export const CANONICAL_LOCAL_SEED = Object.freeze({
  schemaVersion: 'canonical-local-seed@2' as const,
  serviceActor: Object.freeze({
    user: UserSchema.parse({
      id: 'usr_caretaker_service',
      displayName: 'Caretaker service',
      createdAt: CREATED_AT,
    }),
    memberships: Object.freeze([
      MembershipSchema.parse({
        id: 'mem_caretaker_rocky',
        organizationId: 'org_rocky_roost',
        userId: 'usr_caretaker_service',
        role: 'operator',
        grants: [],
        createdAt: CREATED_AT,
        revokedAt: null,
      }),
      MembershipSchema.parse({
        id: 'mem_caretaker_mirror',
        organizationId: 'org_mirror_nest',
        userId: 'usr_caretaker_service',
        role: 'operator',
        grants: [],
        createdAt: CREATED_AT,
        revokedAt: null,
      }),
    ] as const),
  }),
  primary: Object.freeze({
    organization: OrganizationSchema.parse({
      id: 'org_rocky_roost',
      slug: 'rockys-trash-palace',
      name: "Rocky's Trash Palace, Inc.",
      labTenant: true,
      createdAt: CREATED_AT,
    }),
    user: UserSchema.parse({
      id: 'usr_rocky_founder',
      displayName: 'Rocky',
      createdAt: CREATED_AT,
    }),
    membership: MembershipSchema.parse({
      id: 'mem_rocky_owner',
      organizationId: 'org_rocky_roost',
      userId: 'usr_rocky_founder',
      role: 'owner',
      grants: [],
      createdAt: CREATED_AT,
      revokedAt: null,
    }),
    palace: PalaceSchema.parse({
      id: 'pal_sacred_dumpster',
      organizationId: 'org_rocky_roost',
      name: 'Sacred Dumpster Palace',
      timezone: 'America/New_York',
      batteryAvailablePercentage: 62,
      createdAt: CREATED_AT,
    }),
    crewMember: CrewMemberSchema.parse({
      id: 'crew_rocky_founder',
      organizationId: 'org_rocky_roost',
      palaceId: 'pal_sacred_dumpster',
      userId: 'usr_rocky_founder',
      displayName: 'Rocky',
      active: true,
    }),
    schedules: Object.freeze([
      CrewScheduleSchema.parse({
        id: 'sch_rocky_night_shift',
        organizationId: 'org_rocky_roost',
        palaceId: 'pal_sacred_dumpster',
        crewMemberId: 'crew_rocky_founder',
        active: true,
        version: 2,
        timezone: 'America/New_York',
        windowStart: '00:00',
        windowEnd: '03:00',
      }),
    ]),
    preferences: Object.freeze([
      CrewPreferenceSchema.parse({
        id: 'pref_rocky_homecoming',
        organizationId: 'org_rocky_roost',
        palaceId: 'pal_sacred_dumpster',
        crewMemberId: 'crew_rocky_founder',
        kind: 'homecoming_comfort',
        active: true,
        version: 4,
        targetCelsius: 22,
        pathwayLightingIntensityPercent: 60,
        pathwayLightingDurationSeconds: 1_800,
      }),
    ]),
    identityTags: Object.freeze(
      [
        {
          id: 'tag_rocky_verified',
          organizationId: 'org_rocky_roost',
          crewMemberId: 'crew_rocky_founder',
          label: "Rocky's verified tag",
          verified: true,
          active: true,
          version: 4,
        },
        {
          id: 'tag_unknown_guest',
          organizationId: 'org_rocky_roost',
          crewMemberId: null,
          label: 'Unknown tag',
          verified: false,
          active: true,
          version: 1,
        },
        {
          id: 'tag_acorn_hauler',
          organizationId: 'org_rocky_roost',
          crewMemberId: null,
          label: 'Acorn Sanitation hauler',
          verified: true,
          active: true,
          version: 1,
        },
      ].map((value) => IdentityTagSchema.parse(value)),
    ),
    devices: Object.freeze(
      [
        {
          id: 'dev_front_lock',
          organizationId: 'org_rocky_roost',
          palaceId: 'pal_sacred_dumpster',
          kind: 'lock',
          name: 'Front hatch lock',
          health: 'online',
          version: 9,
        },
        {
          id: 'dev_path_lights',
          organizationId: 'org_rocky_roost',
          palaceId: 'pal_sacred_dumpster',
          kind: 'pathway_light',
          name: 'Moonlit pathway lights',
          health: 'online',
          version: 7,
        },
        {
          id: 'dev_thermostat',
          organizationId: 'org_rocky_roost',
          palaceId: 'pal_sacred_dumpster',
          kind: 'thermostat',
          name: 'Nest thermostat',
          health: 'online',
          version: 12,
        },
        {
          id: 'dev_battery_meter',
          organizationId: 'org_rocky_roost',
          palaceId: 'pal_sacred_dumpster',
          kind: 'battery_meter',
          name: 'Battery meter',
          health: 'online',
          version: 5,
        },
        {
          id: 'dev_service_hatch_lock',
          organizationId: 'org_rocky_roost',
          palaceId: 'pal_sacred_dumpster',
          kind: 'service_hatch_lock',
          name: 'Exterior service hatch',
          health: 'online',
          version: 1,
        },
        {
          id: 'dev_residential_hatch',
          organizationId: 'org_rocky_roost',
          palaceId: 'pal_sacred_dumpster',
          kind: 'residential_hatch_lock',
          name: 'Residential hatch',
          health: 'online',
          version: 1,
        },
      ].map((value) => DeviceSchema.parse(value)),
    ),
    capabilities: Object.freeze(
      [
        {
          id: 'cap_lock_state',
          organizationId: 'org_rocky_roost',
          deviceId: 'dev_front_lock',
          kind: 'lock_desired_state',
          enabled: true,
          constraints: { maxUnlockSeconds: 300, requiresVerifiedIdentity: true },
        },
        {
          id: 'cap_path_lighting',
          organizationId: 'org_rocky_roost',
          deviceId: 'dev_path_lights',
          kind: 'pathway_lighting',
          enabled: true,
          constraints: { maxIntensityPercent: 100, maxDurationSeconds: 3_600 },
        },
        {
          id: 'cap_temperature',
          organizationId: 'org_rocky_roost',
          deviceId: 'dev_thermostat',
          kind: 'temperature_target',
          enabled: true,
          constraints: { minimumCelsius: 5, maximumCelsius: 35 },
        },
        {
          id: 'cap_battery_projection',
          organizationId: 'org_rocky_roost',
          deviceId: 'dev_battery_meter',
          kind: 'battery_projection',
          enabled: true,
          constraints: { availablePercentage: 62 },
        },
        {
          id: 'cap_service_hatch_access',
          organizationId: 'org_rocky_roost',
          deviceId: 'dev_service_hatch_lock',
          kind: 'service_hatch_access',
          enabled: true,
          constraints: { maximumAccessSeconds: 900 },
        },
        {
          id: 'cap_residential_hatch_lock',
          organizationId: 'org_rocky_roost',
          deviceId: 'dev_residential_hatch',
          kind: 'residential_hatch_lock_state',
          enabled: true,
          constraints: { requiredState: 'locked' },
        },
      ].map((value) => CapabilitySchema.parse(value)),
    ),
    routine: RoutineSchema.parse({
      id: 'rtn_midnight_entry',
      organizationId: 'org_rocky_roost',
      palaceId: 'pal_sacred_dumpster',
      name: 'Midnight Entry',
      activeVersionId: 'rtv_midnight_entry_v3',
      createdAt: '2026-08-02T00:00:00-04:00',
    }),
    routineVersion: RoutineVersionSchema.parse({
      id: 'rtv_midnight_entry_v3',
      routineId: 'rtn_midnight_entry',
      organizationId: 'org_rocky_roost',
      version: 3,
      status: 'active',
      definition: {
        name: 'Midnight Entry v3',
        trigger: {
          type: 'verified_arrival',
          windowStart: '00:00',
          windowEnd: '03:00',
          timezone: 'America/New_York',
        },
        actions: [
          { type: 'preheat', targetCelsius: 18, completeBy: '02:00' },
          {
            type: 'pathway_lighting',
            intensityPercent: 25,
            durationSeconds: 600,
            beginsAfter: 'verified_arrival',
          },
          { type: 'unlock', durationSeconds: 90, requireVerifiedIdentity: true },
          { type: 'lock_desired_state', afterUnlockSeconds: 90 },
        ],
        constraints: {
          projectedBatteryUseMaxPercentagePoints: 15,
          hardInvariantIds: ['verified_identity_required_for_unlock'],
        },
        projectedBatteryUsePercentagePoints: 9.8,
      },
      sourcePlanId: null,
      sourcePlanHash: null,
      createdAt: '2026-08-12T00:00:00-04:00',
    }),
    haulerRoutine: RoutineSchema.parse({
      id: 'rtn_old_hauler_access',
      organizationId: 'org_rocky_roost',
      palaceId: 'pal_sacred_dumpster',
      name: 'Old hauler access',
      activeVersionId: 'rtv_old_hauler_access_v1',
      createdAt: '2026-08-12T00:00:00-04:00',
    }),
    haulerRoutineVersion: RoutineVersionSchema.parse({
      id: 'rtv_old_hauler_access_v1',
      routineId: 'rtn_old_hauler_access',
      organizationId: 'org_rocky_roost',
      version: 1,
      status: 'active',
      definition: {
        name: 'Old hauler access',
        trigger: {
          type: 'scheduled_access_window',
          windowStart: '08:30',
          windowEnd: '10:30',
          timezone: 'America/New_York',
          authorizedIdentityTagId: 'tag_acorn_hauler',
        },
        actions: [
          {
            type: 'grant_service_hatch_access',
            durationSeconds: 600,
            requireVerifiedIdentity: true,
            compartment: 'service_hatch',
          },
          { type: 'lock_service_hatch', atWindowEnd: true },
        ],
        constraints: {
          serviceHatchOnly: true,
          residentialHatchMustRemainLocked: true,
          finalServiceHatchState: 'locked',
          hardInvariantIds: HARD_INVARIANTS.map((invariant) => invariant.id),
        },
        projectedBatteryUsePercentagePoints: 2,
      },
      sourcePlanId: null,
      sourcePlanHash: null,
      createdAt: '2026-08-12T00:00:00-04:00',
    }),
  }),
  mirror: Object.freeze({
    organization: OrganizationSchema.parse({
      id: 'org_mirror_nest',
      slug: 'mirror-night-crew',
      name: 'Mirror Night Crew, LLC',
      labTenant: false,
      createdAt: CREATED_AT,
    }),
    user: UserSchema.parse({
      id: 'usr_mirror_owner',
      displayName: 'Mira',
      createdAt: CREATED_AT,
    }),
    membership: MembershipSchema.parse({
      id: 'mem_mirror_owner',
      organizationId: 'org_mirror_nest',
      userId: 'usr_mirror_owner',
      role: 'owner',
      grants: [],
      createdAt: CREATED_AT,
      revokedAt: null,
    }),
    palace: PalaceSchema.parse({
      id: 'pal_mirror_dumpster',
      organizationId: 'org_mirror_nest',
      name: 'Sacred Dumpster Palace',
      timezone: 'America/New_York',
      batteryAvailablePercentage: 71,
      createdAt: CREATED_AT,
    }),
    routine: RoutineSchema.parse({
      id: 'rtn_mirror_homecoming',
      organizationId: 'org_mirror_nest',
      palaceId: 'pal_mirror_dumpster',
      name: 'Night Shift Homecoming',
      activeVersionId: 'rtv_mirror_homecoming_v1',
      createdAt: '2026-08-05T00:00:00-04:00',
    }),
    routineVersion: RoutineVersionSchema.parse({
      id: 'rtv_mirror_homecoming_v1',
      routineId: 'rtn_mirror_homecoming',
      organizationId: 'org_mirror_nest',
      version: 1,
      status: 'active',
      definition: {
        name: 'Night Shift Homecoming',
        trigger: {
          type: 'verified_arrival',
          windowStart: '00:00',
          windowEnd: '03:00',
          timezone: 'America/New_York',
        },
        actions: [
          { type: 'preheat', targetCelsius: 20, completeBy: '02:00' },
          {
            type: 'pathway_lighting',
            intensityPercent: 40,
            durationSeconds: 900,
            beginsAfter: 'verified_arrival',
          },
          { type: 'unlock', durationSeconds: 90, requireVerifiedIdentity: true },
          { type: 'lock_desired_state', afterUnlockSeconds: 90 },
        ],
        constraints: {
          projectedBatteryUseMaxPercentagePoints: 15,
          hardInvariantIds: ['verified_identity_required_for_unlock'],
        },
        projectedBatteryUsePercentagePoints: 13.2,
      },
      sourcePlanId: null,
      sourcePlanHash: null,
      createdAt: '2026-08-05T00:00:00-04:00',
    }),
  }),
})
