ALTER TABLE "outbox_messages" DROP CONSTRAINT "outbox_messages_reference_shape";--> statement-breakpoint
ALTER TABLE "outbox_messages" DROP CONSTRAINT "outbox_messages_reference_payload_only";--> statement-breakpoint
ALTER TABLE "outbox_messages" ADD CONSTRAINT "outbox_messages_reference_shape" CHECK (
        ("outbox_messages"."topic" = 'gateway.dispatch' AND "outbox_messages"."mission_id" IS NULL AND "outbox_messages"."operation_id" IS NOT NULL AND "outbox_messages"."execution_id" IS NULL AND "outbox_messages"."command_id" IS NOT NULL AND "outbox_messages"."dispatch_generation" > 0)
        OR ("outbox_messages"."topic" = 'gateway.effect.reconcile' AND "outbox_messages"."mission_id" IS NULL AND "outbox_messages"."operation_id" IS NOT NULL AND "outbox_messages"."execution_id" IS NULL AND "outbox_messages"."command_id" IS NOT NULL AND "outbox_messages"."dispatch_generation" > 0)
        OR ("outbox_messages"."topic" = 'execution.deadline' AND "outbox_messages"."mission_id" IS NOT NULL AND "outbox_messages"."operation_id" IS NOT NULL AND "outbox_messages"."execution_id" IS NOT NULL AND "outbox_messages"."command_id" IS NULL AND "outbox_messages"."dispatch_generation" IS NULL)
        OR ("outbox_messages"."topic" = 'execution.identity-arrival' AND "outbox_messages"."mission_id" IS NOT NULL AND "outbox_messages"."operation_id" IS NOT NULL AND "outbox_messages"."execution_id" IS NOT NULL AND "outbox_messages"."command_id" IS NULL AND "outbox_messages"."dispatch_generation" IS NULL)
        OR ("outbox_messages"."topic" IN ('mission.resume', 'mission.verify') AND "outbox_messages"."mission_id" IS NOT NULL AND "outbox_messages"."operation_id" IS NULL AND "outbox_messages"."execution_id" IS NULL AND "outbox_messages"."command_id" IS NULL AND "outbox_messages"."dispatch_generation" IS NULL)
        OR ("outbox_messages"."topic" = 'operation.reconcile' AND "outbox_messages"."mission_id" IS NULL AND "outbox_messages"."operation_id" IS NOT NULL AND "outbox_messages"."execution_id" IS NULL AND "outbox_messages"."command_id" IS NULL AND "outbox_messages"."dispatch_generation" IS NULL)
      );--> statement-breakpoint
ALTER TABLE "outbox_messages" ADD CONSTRAINT "outbox_messages_reference_payload_only" CHECK (
        ("outbox_messages"."topic" IN ('gateway.dispatch', 'gateway.effect.reconcile') AND "outbox_messages"."payload" = jsonb_build_object('organizationId', "outbox_messages"."organization_id", 'operationId', "outbox_messages"."operation_id", 'commandId', "outbox_messages"."command_id", 'generation', "outbox_messages"."dispatch_generation"))
        OR ("outbox_messages"."topic" = 'execution.deadline' AND "outbox_messages"."payload" = jsonb_build_object('organizationId', "outbox_messages"."organization_id", 'missionId', "outbox_messages"."mission_id", 'operationId', "outbox_messages"."operation_id", 'executionId', "outbox_messages"."execution_id"))
        OR ("outbox_messages"."topic" = 'execution.identity-arrival' AND "outbox_messages"."payload" = jsonb_build_object('organizationId', "outbox_messages"."organization_id", 'missionId', "outbox_messages"."mission_id", 'operationId', "outbox_messages"."operation_id", 'executionId', "outbox_messages"."execution_id", 'evidenceId', "outbox_messages"."payload" ->> 'evidenceId') AND "outbox_messages"."payload" ->> 'evidenceId' ~ '^evd_[a-z0-9][a-z0-9_-]{7,63}$')
        OR ("outbox_messages"."topic" IN ('mission.resume', 'mission.verify') AND "outbox_messages"."payload" = jsonb_build_object('organizationId', "outbox_messages"."organization_id", 'missionId', "outbox_messages"."mission_id"))
        OR ("outbox_messages"."topic" = 'operation.reconcile' AND "outbox_messages"."payload" = jsonb_build_object('organizationId', "outbox_messages"."organization_id", 'operationId', "outbox_messages"."operation_id"))
      );